### ISSUE TITLE
Wrong link to GitHub

### ISSUE THREAD

**Issue by Sebbl22** [jessehouwing/azure-pipelines-agent-screenshot#1]
Hi,
The link in the Readme.md / Azure DevOps Marketplace to GitHub is wrong.
``
If you like this extension, please leave a review and feedback. If you'd have suggestions or an issue, please [file an issue to give me a chance to fix it](https://github.com/jessehouwing/jessehouwing/azure-pipelines-agent-screenshot/issues).``

Correct:
``
If you like this extension, please leave a review and feedback. If you'd have suggestions or an issue, please [file an issue to give me a chance to fix it](https://github.com/jessehouwing/azure-pipelines-agent-screenshot/issues).
``

**Comment by jessehouwing** [comment]
Tx! fixed!
